services:
  db:
    image: mysql:${MYSQL_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    networks:
      - wp-network

  wordpress:
    image: wordpress:${WORDPRESS_IMAGE_TAG}
    container_name: ${COMPOSE_PROJECT_NAME}_wordpress
    depends_on:
      - db
    volumes:
      - ./wordpress:/var/www/html
      - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - "${WORDPRESS_PORT}:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_LOCALE: ja
      WORDPRESS_TABLE_PREFIX: wp_
    restart: always
    networks:
      - wp-network

  wp-cli:
    image: wordpress:cli-php${PHP_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_wp-cli
    depends_on:
      - db
      - wordpress
    command: tail -f /dev/null
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    networks:
      - wp-network

volumes:
  db_data:

networks:
  wp-network:
    driver: bridge